#!/bin/bash
CURRENT_PATH=$(pwd)

cd ..
git checkout master
npm run build
mv dist/ $TMPDIR

echo pass build to release branch...
git checkout release
cd ..
git rm -r dist/
release_path=$(pwd)
cd $TMPDIR
mv dist/ $release_path
cd $release_path
git add dist/
git commit -m "autodeploy release"
git push

cd $CURRENT_PATH
node deploy.js