#!/bin/bash
CURRENT_PATH=$(pwd)
BUILD_DIRECTORY='dist/'

cd ..
git checkout master
npm run build
mv $BUILD_DIRECTORY $TMPDIR

echo pass build to release branch...
git checkout release
cd ..
git rm -r $BUILD_DIRECTORY
release_path=$(pwd)
cd $TMPDIR
mv $BUILD_DIRECTORY $release_path
cd $release_path

git status
git add $BUILD_DIRECTORY
git commit -m "autodeploy1 release"
git push
git checkout autodeploy

cd $CURRENT_PATH
node deploy.js